language: node

sudo: required

services:
  - docker

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

install:
  - aws s3 cp public/ s3://console.market-reaction.com/ --recursive --acl public-read